/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/variations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all catalog variations for tag assignment */
        get: operations["listVariations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all stores */
        get: operations["listStores"];
        put?: never;
        /**
         * Register a new store
         * @description Returns the generated api_key exactly once. Hand it to that store's gateway operator to configure as the X-Store-Key header — it cannot be retrieved again afterward.
         */
        post: operations["createStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tags across all stores, for the admin dashboard
         * @description Gated by Auth0 login, not X-Store-Key — the dashboard isn't a gateway and has no per-store key; it authenticates the human instead. Optionally narrow to one store.
         */
        get: operations["listTagsAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all tags for the requesting store
         * @description The gateway polls this endpoint to discover which of its own store's tags need updating. X-Store-Key identifies the store; only that store's tags are returned. The gateway compares content_hash against what it last rendered; if different, it fetches and pushes the new content.
         */
        get: operations["listTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: components["schemas"]["TagId"];
            };
            cookie?: never;
        };
        /**
         * Get desired display state for a single tag
         * @description Only returns the tag if it belongs to the authenticated store.
         */
        get: operations["getTag"];
        /**
         * Create or update a tag's store and variation assignment
         * @description Admin-dashboard action, gated by Auth0 login (not X-Store-Key). Creates the tag if it does not exist, owned by store_id. Pass variation_id to assign a catalog variation; pass null to unassign. A tag's store cannot be changed once set. content_hash is recomputed immediately so the gateway picks up the change on its next poll.
         */
        put: operations["assignTag"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tag_id}/locate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: components["schemas"]["TagId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Flash a tag's LED so staff can find it on the shelf
         * @description Admin-dashboard action, gated by Auth0 login. Queues a Locate command on the gateway's command queue (api/central-esl-api.yaml) — the flash never changes the screen and sits outside the per-tag version ladder. The response is immediate; the LED flashes on the gateway's next poll.
         */
        post: operations["locateTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tag_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: components["schemas"]["TagId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gateway reports what it successfully rendered
         * @description Called by the gateway after it has pushed content to the physical tag. Only works for a tag belonging to the authenticated store. The service records the confirmation timestamp and battery level.
         */
        post: operations["confirmTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 12-character hex tag identifier (matches the ESL hardware id). Case-insensitive on input, uppercase on output. Anything that is not 12 hex characters is rejected with 400. */
        TagId: string;
        Store: {
            id: string;
            name: string;
            /** @description Square location this store maps to, for resolving per-location price overrides */
            square_location_id: string;
        };
        StoreCreateBody: {
            id: string;
            name: string;
            square_location_id: string;
        };
        StoreWithKey: components["schemas"]["Store"] & {
            /** @description Pass this as X-Store-Key. Shown only once. */
            api_key: string;
        };
        Tag: {
            id: components["schemas"]["TagId"];
            store_id: string;
            /** @description Square catalog variation ID this tag is assigned to */
            variation_id?: string | null;
            /** @description Product name from the Square catalog */
            name?: string | null;
            variation_name?: string | null;
            sku?: string | null;
            /** @description Price in smallest currency unit (e.g. cents), resolved for this tag's store (Square location price overrides applied). Null when pricing_type is VARIABLE_PRICING — the gateway should render placeholder text (e.g. "<name> — See Register") for those, not a price template. */
            price?: number | null;
            /** @enum {string|null} */
            pricing_type?: "FIXED_PRICING" | "VARIABLE_PRICING" | null;
            /** @description SHA-256 of the canonical projection. The gateway uses this to detect drift without re-fetching every tag's full content on every poll. Null means the tag has no variation assigned — the gateway should show its unassigned screen rather than attempt to render product content. Every tag without a variation reports null here, whether it was never assigned or explicitly unassigned. */
            content_hash: string | null;
            /** Format: date-time */
            last_pushed_at?: string | null;
            /** Format: date-time */
            last_confirmed_at?: string | null;
            battery_pct?: number | null;
            /**
             * @description Whether a gateway's access points can currently hear this label, derived from the telemetry they report. `never_heard` means no access point has ever listed it — usually a tag id that does not match any real hardware. `out_of_range` means it was heard once but not within the last hour. `weak` means heard recently at -70 dBm or worse.
             * @enum {string}
             */
            signal?: "ok" | "weak" | "out_of_range" | "never_heard";
            /** @description Last reported signal strength in dBm. Null if never heard. */
            rf_power?: number | null;
            /**
             * Format: date-time
             * @description Last time any access point heard this label.
             */
            last_seen_at?: string | null;
            /** @description Battery reading in volts, converted from the raw tenths-of-a-volt byte the hardware reports. Not a percentage — no discharge curve is assumed. */
            battery_volts?: number | null;
            /** @description Low-battery flag as computed by the gateway. */
            low_battery?: boolean | null;
        };
        TagList: {
            tags: components["schemas"]["Tag"][];
        };
        Variation: {
            id: string;
            item_id: string;
            /** @description Parent item name */
            name: string;
            variation_name: string;
            sku?: string | null;
            /** @description Price in cents. Null when VARIABLE_PRICING. */
            price?: number | null;
            /** @enum {string} */
            pricing_type: "FIXED_PRICING" | "VARIABLE_PRICING";
        };
        VariationList: {
            variations: components["schemas"]["Variation"][];
        };
        AssignBody: {
            /** @description Store this tag belongs to. Immutable once the tag is created. */
            store_id: string;
            /** @description Variation to assign. Null to unassign. */
            variation_id?: string | null;
        };
        LocateBody: {
            /** @description Flash duration. Omit for the gateway's default (30s). The gateway caps this at its own configured maximum (300s). */
            seconds?: number;
        };
        LocateAccepted: {
            /** @description Idempotency key of the queued Locate command */
            update_id: string;
            tag_id: components["schemas"]["TagId"];
            seconds?: number | null;
        };
        ConfirmBody: {
            /** @description Hash of what was actually rendered, for drift detection */
            content_hash: string;
            battery_pct?: number | null;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        Error: {
            detail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listVariations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All known variations with parent item name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariationList"];
                };
            };
        };
    };
    listStores: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stores (api_key omitted — only returned once, on creation) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Store"][];
                };
            };
        };
    };
    createStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreCreateBody"];
            };
        };
        responses: {
            /** @description Store created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreWithKey"];
                };
            };
            /** @description id or square_location_id already in use */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listTagsAdmin: {
        parameters: {
            query?: {
                store_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tags, optionally filtered by store */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagList"];
                };
            };
        };
    };
    listTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tags belonging to the authenticated store */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagList"];
                };
            };
            /** @description Missing or invalid X-Store-Key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: components["schemas"]["TagId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag desired state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description tag_id is not 12 hex characters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Missing or invalid X-Store-Key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Tag not found (or belongs to a different store) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    assignTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: components["schemas"]["TagId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignBody"];
            };
        };
        responses: {
            /** @description Tag after assignment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description tag_id is not 12 hex characters, or the tag already belongs to a different store */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description store_id or variation_id not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    locateTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: components["schemas"]["TagId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LocateBody"];
            };
        };
        responses: {
            /** @description Locate queued for the gateway's next poll */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocateAccepted"];
                };
            };
            /** @description tag_id is not 12 hex characters, or seconds is out of range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Tag not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    confirmTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: components["schemas"]["TagId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmBody"];
            };
        };
        responses: {
            /** @description Confirmation recorded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description tag_id is not 12 hex characters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Missing or invalid X-Store-Key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Tag not found (or belongs to a different store) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
