/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/variations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all catalog variations for tag assignment */
        get: operations["listVariations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all tags with their desired display state
         * @description The gateway polls this endpoint to discover which tags need updating. Returns all known tags. The gateway compares content_hash against what it last rendered; if different, it fetches and pushes the new content.
         */
        get: operations["listTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: components["schemas"]["TagId"];
            };
            cookie?: never;
        };
        /** Get desired display state for a single tag */
        get: operations["getTag"];
        /**
         * Create or update a tag's variation assignment
         * @description Creates the tag if it does not exist. Pass variation_id to assign a catalog variation; pass null to unassign. content_hash is recomputed immediately so the gateway picks up the change on its next poll.
         */
        put: operations["assignTag"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tag_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: components["schemas"]["TagId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gateway reports what it successfully rendered
         * @description Called by the gateway after it has pushed content to the physical tag. The service records the confirmation timestamp and battery level.
         */
        post: operations["confirmTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 16-character uppercase hex tag identifier */
        TagId: string;
        Tag: {
            id: components["schemas"]["TagId"];
            /** @description Square catalog variation ID this tag is assigned to */
            variation_id?: string | null;
            /** @description Product name from the Square catalog */
            name?: string | null;
            variation_name?: string | null;
            sku?: string | null;
            /** @description Price in smallest currency unit (e.g. cents). Null when VARIABLE_PRICING. */
            price?: number | null;
            /** @enum {string|null} */
            pricing_type?: "FIXED_PRICING" | "VARIABLE_PRICING" | null;
            /** @description SHA-256 of the canonical projection. The gateway uses this to detect drift without re-fetching every tag's full content on every poll. */
            content_hash: string | null;
            /** Format: date-time */
            last_pushed_at?: string | null;
            /** Format: date-time */
            last_confirmed_at?: string | null;
            battery_pct?: number | null;
        };
        TagList: {
            tags: components["schemas"]["Tag"][];
        };
        Variation: {
            id: string;
            item_id: string;
            /** @description Parent item name */
            name: string;
            variation_name: string;
            sku?: string | null;
            /** @description Price in cents. Null when VARIABLE_PRICING. */
            price?: number | null;
            /** @enum {string} */
            pricing_type: "FIXED_PRICING" | "VARIABLE_PRICING";
        };
        VariationList: {
            variations: components["schemas"]["Variation"][];
        };
        AssignBody: {
            /** @description Variation to assign. Null to unassign. */
            variation_id?: string | null;
        };
        ConfirmBody: {
            /** @description Hash of what was actually rendered, for drift detection */
            content_hash: string;
            battery_pct?: number | null;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        Error: {
            detail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listVariations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All known variations with parent item name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariationList"];
                };
            };
        };
    };
    listTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagList"];
                };
            };
        };
    };
    getTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: components["schemas"]["TagId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag desired state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Tag not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    assignTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: components["schemas"]["TagId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignBody"];
            };
        };
        responses: {
            /** @description Tag after assignment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description variation_id not found in catalog */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    confirmTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: components["schemas"]["TagId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmBody"];
            };
        };
        responses: {
            /** @description Confirmation recorded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tag not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
